certs:
  domain: dphx.eu
  subdomain: cluster.dphx.eu
  email: benjamin.bachmayr@gmail.com
cluster:
  region: eu-frankfurt-1
base:
  router_domain: router.cluster.dphx.eu
  proxmox_domain: proxmox.cluster.dphx.eu
  authentik_domain: authentik.cluster.dphx.eu
  argocd_domain: argocd.cluster.dphx.eu
  github_clientid: Ov23ligpCNuWq6wQM0wC
  users:
    - username: Ineb01
      name: "Benjamin Bachmayr"
      email: "benjamin.bachmayr@gmail.com"
      superuser: true

applications:
  outpost_kubernetes_integration_id: abb44e34-6bca-4cae-bcf1-ef47fde59e5e