certs:
  domain: dphx.eu
  subdomain: cluster.dphx.eu
  email: benjamin.bachmayr@gmail.com
cluster:
  region: eu-frankfurt-1
  route53_zone: dphx.eu
base:
  router_domain: router.cluster.dphx.eu
  proxmox_domain: proxmox.cluster.dphx.eu
  authentik_domain: authentik.cluster.dphx.eu
  argocd_domain: argocd.cluster.dphx.eu
  github_clientid: Ov23ligpCNuWq6wQM0wC
  users:
    - username: Ineb01
      name: "Benjamin Bachmayr"
      email: "benjamin.bachmayr@gmail.com"
      superuser: true

applications:
  outpost_kubernetes_integration_id: bc5f7e4c-e0e5-4127-81b8-47215f54f61e