remote_state {
  backend = "s3"
  generate = {
    path      = "autogenerated_backend.tf"
    if_exists = "overwrite_terragrunt"
  }
  config = {
    bucket                      = "oci-cluster-terraform-state"
    region                      = "eu-central-1"
    key                         = "oci-cluster/${path_relative_to_include()}.tfstate"
  }
}