include "root" {
  path = find_in_parent_folders()
}

dependency "cluster" {
  config_path = "../cluster"
}

dependency "certs" {
  config_path = "../certs"
}

generate "provider" {
  path = "autogenerated_provider.tf"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
provider "kubernetes" {
  host     = "${dependency.cluster.outputs.kubernetes_host}"

  client_certificate     = <<EOC
${base64decode(dependency.cluster.outputs.client_certificate)}
EOC
  client_key             = <<EOC
${base64decode(dependency.cluster.outputs.client_key)}
EOC
  cluster_ca_certificate = <<EOC
${base64decode(dependency.cluster.outputs.cluster_ca_certificate)}
EOC
}

provider "helm" {
  kubernetes {
    host     = "${dependency.cluster.outputs.kubernetes_host}"

    client_certificate     = <<EOC
${base64decode(dependency.cluster.outputs.client_certificate)}
EOC
    client_key             = <<EOC
${base64decode(dependency.cluster.outputs.client_key)}
EOC
    cluster_ca_certificate = <<EOC
${base64decode(dependency.cluster.outputs.cluster_ca_certificate)}
EOC
  }
}

provider "authentik" {
  url = "https://${yamldecode(file(find_in_parent_folders("config.yaml")))["base"]["authentik_domain"]}"
  token = "${dependency.certs.outputs.authentik_admin_token}"
}

terraform {
  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "2.15.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "2.32.0"
    }
    random = {
      source = "hashicorp/random"
      version = "3.6.3"
    }
    authentik = {
      source = "goauthentik/authentik"
      version = "2024.8.3"
    }
  }
}
EOF
}

inputs = merge(
  yamldecode(file(find_in_parent_folders("config.yaml")))["applications"],
  yamldecode(file(find_in_parent_folders("secrets.yaml")))["applications"],
)