include "root" {
  path = find_in_parent_folders()
}

dependency "secrets" {
  config_path = "../secrets"
}

generate "provider" {
  path = "autogenerated_provider.tf"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  user_ocid    = var.user_ocid
  private_key  = var.private_key
  fingerprint  = var.fingerprint
  region       = var.region
}

terraform {
  required_providers {
    oci = {
      source = "oracle/oci"
      version = "6.9.0"
    }
    ssh = {
      source = "loafoe/ssh"
      version = "2.7.0"
    }
    random = {
      source = "hashicorp/random"
      version = "3.6.3"
    }
  }
}
EOF
}

generate "variables" {
  path = "autogenerated_variables.tf"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
variable "tenancy_ocid" {
  type = string
}

variable "user_ocid" {
  type = string
}

variable "private_key" {
  type = string
}

variable "fingerprint" {
  type = string
}

variable "region" {
  type = string
}
EOF
}

inputs = merge(
  yamldecode(file(find_in_parent_folders("config.yaml")))["cluster"],
  yamldecode(dependency.secrets.outputs.secrets)["cluster"],
)
