include "root" {
  path = find_in_parent_folders()
}

generate "provider" {
  path = "autogenerated_provider.tf"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
provider "proxmox" {
  pm_api_token_id = "root@pam!terraform"
  pm_api_token_secret = "7dd43d8a-bf23-47b4-ac82-590e867b9437"
  pm_api_url = "https://192.168.1.99:8006/api2/json/"
  pm_tls_insecure = true
}
terraform {
  required_providers {
    proxmox = {
      source = "Telmate/proxmox"
      version = "3.0.1-rc4"
    }
    ssh = {
      source = "loafoe/ssh"
      version = "2.7.0"
    }
    random = {
      source = "hashicorp/random"
      version = "3.6.3"
    }
  }
}
EOF
}

inputs = yamldecode(file(find_in_parent_folders("config.yaml")))["cluster"]
