authentik:
  secret_key: ${authentik_token}
  bootstrap_password: ${authentik_admin_pw}
  bootstrap_token: ${authentik_admin_token}
  error_reporting:
    enabled: true
  postgresql:
    password: ${postgres_pw}

server:
  ingress:
    enabled: true
    hosts:
      - ${domain}
    tls:
      - secretName: authentik-tls
        hosts:
          - ${domain}
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"

postgresql:
  enabled: true
  auth:
    password: ${postgres_pw}

redis:
  enabled: true
  