include "root" {
  path = find_in_parent_folders()
}

generate "provider" {
  path = "autogenerated_provider.tf"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
provider "aws" {
}
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.62.0"
    }
  }
}
EOF
}

inputs = yamldecode(file(find_in_parent_folders("config.yaml")))["certs"]
